### ISSUE TITLE
Reconsider your variable strategy

### ISSUE THREAD

**Issue by joostf** [jenniferslagt/web-app-from-scratch-1920#13]
https://github.com/cmda-minor-web/best-practices/blob/master/javascript.md#var-let-or-const

**Comment by jenniferslagt** [comment]
Done! ![bitmoji](https://render.bitstrips.com/v2/cpanel/3c97455d-0ce1-4ac8-82a0-601e6d6f6fd2-83c93cc0-d0ae-4742-a59b-b1a0ec5de8e6-v1.png?transparent=1&palette=1&width=246)
