### ISSUE TITLE
Creating a modules folder to import external code

### ISSUE THREAD

**Issue by qiubee** [jenniferslagt/web-app-from-scratch-1920#8]
I see that your using externing code form another party. To know what code you've made yourself and what you used from other sources, you can create a modules folder and import it to your main file your're working in. For example:

:open_file_folder: Modules
|-
- module.js
- external-party-code.js
 
**In your main file:**
```js
import {module} from "./modules/module.js"
```

**Comment by joostf** [comment]
Or even add an extra folder 'vendor' for third party scripts?
