### ISSUE TITLE
1 grote function losbreken in kleinere functions

### ISSUE THREAD

**Issue by ManoukK** [jenniferslagt/web-app-from-scratch-1920#9]
Je maakt nu gebruik van 1 grote function, misschien is het handig om wat kleinere functions ervan te maken. 

Maar ik snap wel waar om je het hebt gedaan en ik weet niet goed hoe je dit los zo kunnen maken.

**Comment by jenniferslagt** [comment]
Heb een extra functie toegevoegd! Dit is trouwens ook handig om meer overzicht te creëren in je actor / interactive diagram!
